### ISSUE TITLE
Publishing workflow is not works well

### ISSUE THREAD

**Issue by pddg** [textlint/textlint-plugin-latex2e#147]
https://github.com/textlint/textlint-plugin-latex2e/runs/2532777216?check_suite_focus=true#step:5:5

**Comment by pddg** [comment]
```
Run $(npm bin)/can-npm-publish
  $(npm bin)/can-npm-publish
  shell: /bin/bash -e {0}
/home/runner/work/_temp/3f8ca374-4bfd-4be9-bfe1-bd1f73966463.sh: line 1: /home/runner/work/textlint-plugin-latex2e/textlint-plugin-latex2e/node_modules/.bin/can-npm-publish: No such file or directory
Error: Process completed with exit code 127.
```

**Comment by pddg** [comment]
@tani
May I ask you to check it?

**Comment by tani** [comment]
Look at this. The commit cf6dc3e7c3d79d988d084cd18d0b1ec5d7486195 remained the `can-npm-publish`  but the next commit 48cfeaa553afd15f879d1ca2aec204afe927440e dropped `can-npm-publish`. It is curious because the commit diff between two commit does contains the deletion of this package. Any way It is easy to fix it, is just adding `npx can-npm-publish` instead `$(npm bin)/can-npm-publish` in workflow.
